--£ 사원번호가 7788 인 사원과 직위(JOB)가 같은 사원의 이름과 직위를
--표시하세요.표시하세요

SELECT ENAME,JOB FROM EMPLOYEE 
WHERE JOB= ( SELECT JOB FROM EMPLOYEE WHERE ENO =7788 );


--£ 사원번호가(ENO) 7499 인 사원보다 급여가(SALARY) 많은 사원
--이름(ENAME),직위(JOB)를 화면에 표시하세요

SELECT ENAME,JOB FROM EMPLOYEE
WHERE SALARY > (SELECT SALARY FROM EMPLOYEE WHERE ENO = 7499 );


--£ 최소(MIN) 급여를(SALARY) 받는 사원의 이름,(ENAME), 직위(JOB) 및 급여를
--표시하세요.

SELECT ENAME,JOB,SALARY FROM EMPLOYEE
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEE);
