--£ 테이블 컬럼 크기 변경하기
--① 예제) 부서테이블(DEPT) BIRTH 컬럼 삭제하기
--DDL문 : CREATE TABLE~, ALTER TEBLE~ , RENAME~
--DML문: CUD,INSERT/UPDATE/DELETE  
--TCL문: ROLLBACK/COMMIT


ALTER TABLE DEPT_SAMPLE 
DROP COLUMN BIRTH;