CREATE TABLE EMP_INSERT
AS
SELECT * FROM EMPLOYEE
WHERE 1=2;

INSERT INTO EMP_INSERT(ENO,ENAME,JOB,MANAGER,HIREDATE,SALARY,COMMISSION,DNO)
VALUES(1,'KTG','STUDENT',NULL,SYSDATE,2700,230,10);
COMMIT;
SELECT * FROM EMP_INSERT;


--£ EMPLOYEE 테이블을 복사하여 EMP_COPY 란 이름의 테이블을 만드세요.
--단, 데이터도 포함해서 만드세요(CTAS)
--EMP_COPY 테이블이 있으면 테이블을 삭제하고 다시 만드세요

CREATE TABLE EMP_COPY
AS
SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;


--£ EMP_COPY 테이블에서 사원번호가(ENO) 7788 인 사원의 부서번호를(DNO)
--10 번으로 수정하세요.

UPDATE EMP_COPY 
SET
DNO=10
WHERE ENO=7788;
COMMIT;
SELECT * FROM EMP_COPY;