--£ EMPLOYEE 테이블 복사하여 EMP_SAMPLE 빈 테이블을 만드세요
--사원 테이블의 사원번호(ENO)에 PRIMARY KEY 제약조건을 지정하되, 
--제약 조건 이름은 PK_MY_EMP 하시오


CREATE TABLE EMP_SAMPLE
AS
SELECT * FROM EMPLOYEE
WHERE 1=2;

ALTER TABLE EMP_SAMPLE
ADD CONSTRAINT PK_MY_EMP PRIMARY KEY(ENO);


--£ DEPARTMENT 테이블 복사하여 DEPT_SAMPLE 빈 테이블을 만드세요
--부서번호(DNO)에 PRIMARY KEY 제약조건을 지정하되, 제약조건 이름은
--PK_MY_DEPT 하세요

CREATE TABLE DEPT_SAMPLE
AS
SELECT * FROM DEPARTMENT
WHERE 1=2;

ALTER TABLE DEPT_SAMPLE
ADD CONSTRAINT PK_MY_DEPT PRIMARY KEY(DNO);

